
# WARNING: May be untested .

name: test


# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none



on:
  push:
  workflow_dispatch:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    #- cron: '5 1 * * 6'
    #- cron: '5 1 * * 2,4'
    #- cron: '5 1 * * 2'
    #- cron: '5 1 * * 4'
    #- cron: '5 1 * * 5'
    - cron: '5 1 * * 1'

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_latest:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04
    #runs-on: ubuntu-18.04
    steps:
      - name: users
        shell: bash
        run: |
          sudo -u ubuntu -n bash -c 'sudo -n useradd runner --non-unique -u $UID -g $UID' || true
          sudo -u ubuntu -n bash -c 'sudo -n groupadd runner --non-unique -g $UID' || true
          sudo -u runner -n bash -c 'sudo -n echo $USER $UID' || true
          true
      - name: Maximize build space
        if: ${{ github.event.inputs.runnerName != 'ubuntu-latest-m' }}
        uses: easimon/maximize-build-space@master
        with:
          ##root-reserve-mb: 512
          ##root-reserve-mb: 1450
          ##root-reserve-mb: 950
          #root-reserve-mb: 1750
          #root-reserve-mb: 1625
          root-reserve-mb: 28000
          ##temp-reserve-mb: 100
          ##temp-reserve-mb: 300
          ##temp-reserve-mb: 300
          #temp-reserve-mb: 700
          temp-reserve-mb: 50
          ##swap-size-mb: 128
          ##swap-size-mb: 192
          #swap-size-mb: 8
          swap-size-mb: 2
          #swap-size-mb: 384
          #remove-dotnet: ${{ github.event.inputs.runnerName != 'ubuntu-latest-m' }}
          remove-dotnet: 'true'
          #remove-android: ${{ github.event.inputs.runnerName != 'ubuntu-latest-m' }}
          remove-android: 'true'
          #remove-haskell: ${{ github.event.inputs.runnerName != 'ubuntu-latest-m' }}
          remove-haskell: 'true'
          #remove-codeql: ${{ github.event.inputs.runnerName != 'ubuntu-latest-m' }}
          remove-codeql: 'true'
          #remove-docker-images: ${{ github.event.inputs.runnerName != 'ubuntu-latest-m' }}
          remove-docker-images: 'true'
    
      - name: _getCore_ub
        shell: bash
        timeout-minutes: 90
        run: |
          mkdir -p ~/core/infrastructure
          cd ~/core/infrastructure
          git clone --depth 1 --recursive https://github.com/mirage335-colossus/ubiquitous_bash.git
          cd ubiquitous_bash
          ./_setupUbiquitous.bat
      - name: _getMinimal_cloud
        shell: bash
        run: |
          ~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _getMinimal_cloud
      - name: _getMost
        shell: bash
        run: |
          ~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _getMost
      - name: _get_from_nix
        shell: bash
        run: |
          ~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _get_from_nix "$USER"
        timeout-minutes: 90
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'recursive'
      - name: _getMinimal_cloud
        shell: bash
        run: |
          ./ubiquitous_bash.sh _getMinimal_cloud
        timeout-minutes: 90


      - name: _test
        shell: bash
        run: |
          ./ubiquitous_bash.sh _test




